apache:
    container_name: apache
    hostname: jbox_docker
    build: ./apache
    expose:
        - "80"
        - "443"
    ports:
        - "80:80"
    volumes_from:
        - dataphp
        - dataapache

dataphp:
    image: alpine:3.5
    volumes:
        - ./www:/var/www

dataapache:
    image: alpine:3.5
    volumes:
        - ./apache/logs/apache2:/var/log/apache2
        - ./apache/sites-enabled:/etc/apache2/sites-enabled

