apache:
    container_name: apache
    hostname: jbox_docker
    build: ./apache
    expose:
        - "80"
    links:
        - web:web
    ports:
        - "80:80"
    volumes_from:
        - dataphp
        - dataapache

web:
    container_name: web
    build: ./web
    volumes_from:
        - dataphp

dataphp:
    image: debian:jessie
    volumes:
        - ./www:/var/www

dataapache:
    image: alpine:3.5
    volumes:
        - ./apache/logs/apache2:/var/log/apache2
        - ./apache/sites-enabled:/etc/apache2/sites-enabled
