mysql56:
  container_name: mysql56
  build: ./db/mysql56
  ports:
    - "3306:3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: vagrant
    MYSQL_USER: vagrant
    MYSQL_PASSWORD: vagrant
    MYSQL_DATABASE: myapp
  volumes:
    - ./db/mysql56/data:/var/lib/mysql
    - ./db/mysql56/logs:/var/log/mysql
  command: 
    - usermod -u 1000 mysql

mysql57:
  container_name: mysql57
  build: ./db/mysql57
  ports:
    - "3307:3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: vagrant
    MYSQL_USER: vagrant
    MYSQL_PASSWORD: vagrant
    MYSQL_DATABASE: myapp
  volumes:
    - ./db/mysql57/data:/var/lib/mysql
    - ./db/mysql57/logs:/var/log/mysql
  command:
    - usermod -u 1000 mysql

mariadb:
  container_name: mariadb
  image: mariadb
  ports:
    - "3308:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=vagrant
    - MYSQL_USER=vagrant
    - MYSQL_PASSWORD=vagrant
    - MYSQL_DATABASE=myapp
  volumes:
    - ./db/mariadb/data:/var/lib/mysql
    - ./db/mariadb/logs:/var/log/mysql

mongo:
  container_name: mongo
  image: mongo
  volumes:
    - ./db/mongo/data:/data/db

solr:
    image: solr
    ports:
        - "8983:8983"
    volumes:
        # before running create solr/data and chown 8983:8983 it.
        - ./db/solr/data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore

redis:
    image: redis
    ports:
        - "6379:6379"
    volumes:
        - ./db/redis/data:/data

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - mysql56:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: vagrant
    MYSQL_ROOT_PASSWORD: vagrant

apache:
    container_name: apache
    hostname: jbox_docker
    build: ./apache
    expose:
        - "80"
    links:
        - web:web
    ports:
        - "80:80"
    volumes_from:
        - dataphp
        - dataapache

web:
    container_name: web
    build: ./web
    links:
        - mysql56:mysql56
        - mongo:mongo
        - redis:redis
    volumes_from:
        - dataphp

dataphp:
    image: debian:jessie
    volumes:
        - ./www:/var/www

dataapache:
    image: alpine:3.5
    volumes:
        - ./apache/logs/apache2:/var/log/apache2
        - ./apache/sites-enabled:/etc/apache2/sites-enabled
