db:
  build: ./mysql
  ports:
    - "3306:3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: vagrant
    MYSQL_USER: vagrant
    MYSQL_PASSWORD: vagrant
    MYSQL_DATABASE: myapp
  volumes:
    - ./mysql/db:/var/lib/mysql
    - ./mysql/logs:/var/log/mysql
  command: 
    - usermod -u 1000 mysql

